[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Caussz", email = "cczcaua@gmail.com"},
]
dependencies = [
    "openai>=1.3.5",
    "dotenv>=0.0.5",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

